# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = {$DB_USER}
quarkus.datasource.password = {$DB_SENHA}
quarkus.datasource.jdbc.url = {DB-URL}

# desabilitar o docker 
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
# quarkus.hibernate-orm.database.generation=none
# quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# JWT
mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=sga-api
smallrye.jwt.sign.key.location=private.pem

quarkus.oidc.auth-server-url={}
quarkus.oidc.client-id={}
quarkus.oidc.credentials.secret={}
keycloak.admin.server-url={}
keycloak.admin.target-realm={}