@startuml violoes
!define RECTANGLE
skinparam classAttributeIconSize 0

'Essa classe é genérica pois cada classe Service terá a sua própria interface
interface Service<T> {
    + listAll(): List<T>
    + findById(id: Long): T
    + findByName(name: String): List<T>
    + create(entity: T): T
    + update(id: Long, entity: T): T
    + deleteById(id: Long): void
}

Abstract class Violao {
  - id: Long
  - nome: String
  - precoBase: BigDecimal
  - anoFabricacao: Integer
}

together{
  class ViolaoAco {
  }
  enum GaugeCorda {
    EXTRA_LIGHT
    LIGHT
    MEDIUM
    HEAVY
  }

}

together{
  class ViolaoNylon {
  }
  enum TensaoCorda {
    BAIXA
    MEDIA
    ALTA
  }
}

class Marca {
  - id: Long
  - nome: String
  - paisOrigem: String
  - website: String
}

class PerfilBraco {
  - id: Long
  - nome: String
  - formato: String
  - espessura: Double
}

class Madeira {
  - id: Long
  - tipo: String
  - densidade: String
  - sonoridade: String
}

class Acessorio {
  - id: Long
  - nome: String
  - descricao: String
  - quantidadeEstoque: Integer
  - precoUnitario: BigDecimal
}

' Relacionamentos
Service <|.. Violao
Service <|.. Marca
Service <|.. Madeira
Service <|.. Acessorio
Service <|.. PerfilBraco

Violao <|-down- ViolaoNylon
Violao <|-down- ViolaoAco

Violao "*" o-- "1" PerfilBraco
Violao "*" -up-> "1" Marca

ViolaoNylon -[hidden]- TensaoCorda
ViolaoNylon *-- TensaoCorda
ViolaoAco -[hidden]- GaugeCorda
ViolaoAco *-- GaugeCorda

Violao "1" o-left- "*" Madeira

Violao "*" o--right- "*" Acessorio

@enduml